# -*- coding: utf-8 -*-
"""tradingview

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxZieSaWcwNd3FtvVnLFxeDoMbPAR_dp
"""

!pip install selenium
!pip install webdriver_manager
!pip install tradingview-ta

from tradingview_ta import TA_Handler, Interval, Exchange

tesla = TA_Handler(
    symbol="TSLA",
    screener="america",
    exchange="NASDAQ",
    interval=Interval.INTERVAL_1_DAY
)
print(tesla.get_analysis().summary)
# Example output: {"RECOMMENDATION": "BUY", "BUY": 8, "NEUTRAL": 6, "SELL": 3}

import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

ticker = 'TSLA'
interval = '1M'

# Set up chromedriver
options = Options()
options.add_argument("--headless")
webdriver = webdriver.Chrome(ChromeDriverManager().install(), options = options)

# Declare list variable
analysis = []

try:
    # Open tradingview's site
    webdriver.get("https://s.tradingview.com/embed-widget/technical-analysis/?locale=en#%7B%22interval%22%3A%22{}%22%2C%22width%22%3A%22100%25%22%2C%22isTransparent%22%3Afalse%2C%22height%22%3A%22100%25%22%2C%22symbol%22%3A%22{}%22%2C%22showIntervalTabs%22%3Atrue%2C%22colorTheme%22%3A%22dark%22%2C%22utm_medium%22%3A%22widget_new%22%2C%22utm_campaign%22%3A%22technical-analysis%22%7D".format(interval, ticker))
    webdriver.refresh()
    time.sleep(1)
    
    # Recommendation
    recommendation_element = webdriver.find_element_by_class_name("speedometerSignal-pyzN--tL")
    analysis.append(recommendation_element.get_attribute('innerHTML'))
    
    # Counters
    counter_elements = webdriver.find_elements_by_class_name("counterNumber-3l14ys0C")
    
    # Sell, Neutral, and Buy Signal Counts
    analysis.append(int(counter_elements[0].get_attribute('innerHTML')))
    analysis.append(int(counter_elements[1].get_attribute('innerHTML')))
    analysis.append(int(counter_elements[2].get_attribute('innerHTML')))
    
    # Set up DataFrame
    df = pd.DataFrame.from_records([tuple(analysis)], columns=['Overall Recommendation', '# of Sell Signals', '# of Neutral Signals', '# of Buy Signals'])
    df['Ticker'] = [ticker]
    print (df.set_index('Ticker').T)

except Exception as e:
    print (f'Could not get the recommendation due to {e}')

